import numpy as np
from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

BATTLE_PREPARATION = Button(area={'cn': (1031, 624, 1228, 682), 'en': (1031, 624, 1228, 682), 'jp': (1030, 623, 1229, 683), 'tw': (1031, 624, 1228, 682)}, color={'cn': (np.int64(216), np.int64(159), np.int64(83)), 'en': (np.int64(216), np.int64(160), np.int64(91)), 'jp': (np.int64(214), np.int64(157), np.int64(83)), 'tw': (np.int64(216), np.int64(159), np.int64(83))}, button={'cn': (1031, 624, 1228, 682), 'en': (1031, 624, 1228, 682), 'jp': (1030, 623, 1229, 683), 'tw': (1031, 624, 1228, 682)}, file={'cn': './assets/cn/os_combat/BATTLE_PREPARATION.png', 'en': './assets/en/os_combat/BATTLE_PREPARATION.png', 'jp': './assets/jp/os_combat/BATTLE_PREPARATION.png', 'tw': './assets/tw/os_combat/BATTLE_PREPARATION.png'})
SIREN_PREPARATION = Button(area={'cn': (1043, 638, 1240, 698), 'en': (1043, 639, 1240, 698), 'jp': (1042, 638, 1241, 699), 'tw': (1047, 641, 1239, 698)}, color={'cn': (np.int64(136), np.int64(94), np.int64(111)), 'en': (np.int64(131), np.int64(85), np.int64(102)), 'jp': (np.int64(136), np.int64(97), np.int64(113)), 'tw': (np.int64(138), np.int64(106), np.int64(121))}, button={'cn': (1043, 638, 1240, 698), 'en': (1043, 639, 1240, 698), 'jp': (1042, 638, 1241, 699), 'tw': (1047, 641, 1239, 698)}, file={'cn': './assets/cn/os_combat/SIREN_PREPARATION.png', 'en': './assets/en/os_combat/SIREN_PREPARATION.png', 'jp': './assets/jp/os_combat/SIREN_PREPARATION.png', 'tw': './assets/tw/os_combat/SIREN_PREPARATION.png'})
